### ISSUE TITLE
ページごとのcss,JSファイルの読み込み方法がわからない

### ISSUE THREAD

**Issue by yuu701** [ryujimorimoto/hello-my-blend#1]
複数人開発をするときに、ページごとにCSS,JSファイルを読み込みたい。

**Comment by ryujimorimoto** [comment]
layout/theme.liquidファイルのheadの閉じタグ直前に、themeタグを使って条件分岐で対応する。
例）assets/top-page.jsファイルをトップページのみに読みこむ場合（assets/top-page.jsファイルは作成）
`{%- if template == 'index' -%}
    <script src="{{ 'top-page.js' | asset_url }}" defer="defer"></script>
    {{ 'top-page.css' | asset_url | stylesheet_tag }}
{%- endif -%}`

**Comment by yuu701** [comment]
OKです。
