### ISSUE TITLE
.liquid拡張子のついていないcssファイルの読み込みについて

### ISSUE THREAD

**Issue by yuu701** [ryujimorimoto/hello-my-blend#3]
ページごとに読み込むcssを分ける際、theme.liquidに
`{%- if template == 'page.about-us' -%}
    <link rel="stylesheet" href="{{ 'about-us.css' | asset_url | split: '?' | first }}">
  {%- endif -%}`
を記述して、about-us.cssを作成した。
今まで記述していたcssは反映されたが、新しく記述したコードが反映できておらず、theme deproyを行っても変わらなかった。
ファイル名をabout-us.css.liquidに変更したら、反映できるようになった。

・about-us.cssが読み込めなかった理由
・今まで記述したコードだけ反映されていた理由
以上2点がわかりません。

**Comment by yuu701** [comment]
カスタマイズ画面ではabout-us.css.liquidで反映されましたが、プレビュー画面では反映されていませんでした。
この原因もよくわからないです。

**Comment by yuu701** [comment]
shopifyのQ＆Aを参考にtheme.liquid内のコードを
`{%- if template == 'page.about-us' -%}
    {{'about-us.css' | asset_url | stylesheet_tag}}
  {%- endif -%}`
に変更してファイル名をcssに変更したら、プレビュー画面もカスタマイズ画面も反映されるようになりました。

**Comment by ryujimorimoto** [comment]
再現できず。
