### ISSUE TITLE
プルリクエストの管理について

### ISSUE THREAD

**Issue by yuu701** [ryujimorimoto/hello-my-blend#4]
１つのブランチに対してプルリクがすでにある場合は、新しくプルリクエストが出せないようなので、新しいブランチを作成して作業した方が良いでしょうか？

**Comment by ryujimorimoto** [comment]
新しいブランチを切らなくても、普通にpushしていただければ大丈夫です。

コミット履歴から、適宜変更箇所を読み取ります^^

**Comment by ryujimorimoto** [comment]
mainブランチにプルリクができなかった原因ですが、
コミットログが全然一致していなかったことが原因でした。

どっかで、.gitフォルダを削除したのかもです。
とりあえず、ログが一致するように修正しておきました。

特に何か作業、修正する必要はないです！

**Comment by yuu701** [comment]
承知いたしました。
