### ISSUE TITLE
pullをするタイミングについて

### ISSUE THREAD

**Issue by yuu701** [ryujimorimoto/hello-my-blend#5]
pullをするタイミングがよくわからないです。
毎日作業後、push
朝作業前に、pullでしょうか？
merge前でもした方が良いのかよくわからないです。

**Comment by ryujimorimoto** [comment]
返信漏れてました。

- [pull ] 
pullは、「変更を取り込む」という作業なので、
誰かの変更を自分のコードに取り込みたい時に行っていただければOKデス。

- [ push ] 
いつしなければならないというルールは特に作りません。
個人的には、毎日作業後にpushするのがいいかとは思います。

- [ commit ] 
commit は、下記のルールで実施して行きタイト思います。
1. 一日の作業終わり
　簡単に「何を、どこまで」書いたかわかるようなコミット名
2. 機能、コンポーネント単位で作成完了時
　簡単に「なんの機能」「なんのコンポーネント」が完成したかわかるコミット名
　例）「ABOUT USのカレーが項目が完成」など。

- [ プルリク ] 
いつプルリクするかは、ルール化したいと思っていますが、
詳細はちょっと検討します。
一旦、機能、コンポーネント単位、ページ単位で完了した時点で、
プルリクをお願いしたいと思います。

**Comment by yuu701** [comment]
確認いたしました。
